[workspace]
members = [
    "android-release-support",
    "rustls-platform-verifier",
]

resolver = "2"

[patch."crates-io"]
rustls = { git = "https://github.com/cpu/rustls", rev = "9d547f70ba60fe3f3b5e68f41f14b9354c545ff1" }
